FROM messense/rust-musl-cross:x86_64-musl

ENV DEBIAN_FRONTEND=noninteractive

# COPY sources.list /etc/apt/sources.list

ENV TZ=Asia/Shanghai

RUN set -eux; \
    apt-get update ; \
    apt-get install -y tzdata ; \
    ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime ; \
    dpkg-reconfigure -f noninteractive tzdata

ENV RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static
ENV RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup

COPY --chown=0755 sccache-0.3.3 /root/.cargo/bin/sccache
ENV SCCACHE_DIR=/root/.cache/sccache
ENV SCCACHE_CACHE_SIZE="3G"

COPY config-sccache.toml /root/.cargo/config

WORKDIR /home/rust/src

