version: "3.7"

services:
  rust-gnu-builder:
    image: rust-gnu-builder
    build:
      context: .
      dockerfile: Dockerfile-gnu
    container_name: rust-gnu-builder
    hostname: rust-gnu-builder
    tty: true
    networks:
      - default

  rust-linux-builder:
    image: rust-linux-builder
    build:
      context: .
      dockerfile: Dockerfile-musl
    container_name: rust-linux-builder
    hostname: rust-linux-builder
    volumes:
      - .:/root/builder
      - ~/.cargo/registry:/root/.cargo/registry
      - ~/.cargo/git:/root/.cargo/git
      - ~/.cache/sccache:/root/.cache/sccache
    tty: true
    networks:
      - default

networks:
  default:
