version: "3.7"

services:
  rust-gnu-builder:
    image: rust-gnu-builder
    build:
      context: .
      dockerfile: Dockerfile-gnu
    container_name: rust-gnu-builder
    hostname: rust-gnu-builder
    tty: true
    networks:
      - default

  rust-musl-builder:
    image: rust-musl-builder
    build:
      context: .
      dockerfile: Dockerfile-musl
    container_name: rust-musl-builder
    hostname: rust-musl-builder
    tty: true
    networks:
      - default

networks:
  default:
